name: ntfy_action
description: Send GitHub Action workflow notifications to ntfy.
branding:
  icon: "upload"
  color: "blue"
inputs:
  url:
    description: "Server URL."
    required: true
    default: "https://ntfy.sh"
  topic:
    description: "NTFY topic."
    required: true
    default: "ntfy_action"
  tags:
    description: "Tags for the message seperated by commas."
    required: false
    default: ""
  title:
    description: "NTFY message title."
    required: false
    default: "GitHub Action"
  basic_auth:
    description: "Authentication using basic method, should just be the secret value."
    required: false
    default: ""
  token_auth:
    description: "Authentication using token method, should just be the secret value."
    required: false
    default: ""
  details:
    description: "Additional text after the notification message."
    required: false
    default: ""
  priority:
    description: "Message priority."
    required: false
    default: 0
  server_type:
    description: "Type of server the actions is used on, values: github or gitea."
    required: false
    default: "github"
  debug:
    description: "Prints debug information for dev/troubleshooting."
    required: false
    default: false
outputs:
  response:
    description: "The response of POST request."
runs:
  using: "node20"
  main: "dist/index.js"
